-- MySQL Script generated by MySQL Workbench
-- mar 09 jul 2019 20:08:01 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema register_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `register_db` ;

-- -----------------------------------------------------
-- Schema register_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `register_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;

USE `register_db` ;

-- -----------------------------------------------------
-- Table `register_db`.`loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `register_db`.`loan` ;

CREATE TABLE IF NOT EXISTS `register_db`.`loan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loan_amount_min` DECIMAL NULL,
  `loan_amount_max` DECIMAL NULL,
  `loan_interest` DECIMAL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `register_db`.`period`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `register_db`.`period` ;

CREATE TABLE IF NOT EXISTS `register_db`.`period` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `period_min` INT NULL,
  `period_max` INT NULL,
  `interest_rate` VARCHAR(45) NULL,
  `loan_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_period_loan_idx` (`loan_id` ASC) VISIBLE,
  CONSTRAINT `fk_period_loan`
    FOREIGN KEY (`loan_id`)
    REFERENCES `register_db`.`loan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


--------------------------------------------------------

INSERT INTO `register_db`.`loan` (`loan_amount_min`, `loan_amount_max`, `loan_interest`) VALUES ('1', '1000', '10');
INSERT INTO `register_db`.`loan` (`loan_amount_min`, `loan_amount_max`, `loan_interest`) VALUES ('1001', '100000', '5');

INSERT INTO `register_db`.`period` (`period_min`, `period_max`, `interest_rate`, `loan_id`) VALUES ('1', '12', 'FLAT', '1');
INSERT INTO `register_db`.`period` (`period_min`, `period_max`, `interest_rate`, `loan_id`) VALUES ('1', '12', 'FLAT', '2');
INSERT INTO `register_db`.`period` (`period_min`, `period_max`, `interest_rate`, `loan_id`) VALUES ('13', '36', 'DECLINING', '2');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
